language: java
jdk: oraclejdk7
sudo: false
env:
  global:
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_BUILD_LABEL=$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-pre-alpha-$TRAVIS_BRANCH
  - HEIMDALL_BRANCH_FOR_DEPLOY=master
  - HEIMDALL_PACKAGE_NAME=hoard-ingest-1.0-SNAPSHOT-dist-assembly.zip
script:
  - mvn clean package -DskipTests
before_deploy:
  - mkdir -p dpl_cd_upload
  - cp target/$HEIMDALL_PACKAGE_NAME dpl_cd_upload
deploy:
  - provider: s3
    access_key_id: &1
      secure: DvbkV6o0z5cxTAWcTzLPhWpBxoPb2obySGkTAOsJN1yIxz0+6c6IDvvd0xCfvWbdTnclZLe+KYbyWJiWKBrmkduNFZfL0etBm3+w9HFXoJyNbTwHFVqJvGM9oaYnyTNTS/VigUIHI4pOW+fq3ZuCRPMkhovLmMlnEMWfaRXAIhAuxhYa35ceCnN/J7OG6DLqWRo5KbeHaPaR6YWjMhr90cGPl8LzsVAoWv+9wooE+LS+qvwAInaHpnFfIxrFxk2LuEoY+xoi6Svd6MFKV2Suw6XrFynaQG/l2tYrwi+jtMnaYK6wzZiDswNWPp6K2nWV9mlNWQWCmVraoXUepHOwfi1qNRCkKNOAIsNqQXVZhmEC3HbxegLnGlp0OBTH6bmYRvCuMIpK0CuuXffybjBN8fpKrfvN03ZzrJzR+Y2Key+hyTiG/4+6bKopq3datBgFowIo0HZHjlrHMjtxnzTsYdqTzo2Hb4KKs3mSUaTUWz2dnfT0ej5qMGDP203q9DKSn/kwObhiCX3QbJowof5dbloF6kJ2uRE8I0rdVEsSNPNfUUhAlzF3QZ+3xNEY0jWfHURkW7aeHZjCh1QTIIF0n3UXIWb0V1dF46qBogQgM18OdqW8bp5fdoaMpL/wSq8c6QTW8qGGbIpVLm8teKZ7O70MKrH4NANHHCy/ZklRJFY=
    secret_access_key: &2
      secure: szsqdEMwi7a23BTZyVyShkMCgfsBLVvaS+zZrFzE3KWT5EhklVPIg1r/7ohC68lm2vDtuVc75ZNyu5uxiDeAoOJAlPMflPsXRn0K8Kakwm0SxKSG5h9j7aHf701U3dNGRj2ukH2UeinfRyvGlrk7Y+3Z12SMGbE1XGgBeY9sfFNVXWwOUB6D/y+hPjandTOXIR7g1Efeg4ECR6MXlDpcigR4Ql7jbEzkAs/sGo9WoQO6J1oqe0Mld6lbLWE+avxr65UjpFkMVsA2nIrkQi4kLRVeHcXiNxid+q/nmkz0KBu+EIYYez9Pn2pwb8LWHDaheJ+6IkDo0pZvCLerLgnV6zOfl6f5qwmoxMA8HcyJ7l3XqcKyhA3mwMT5Tl0FsloOp1P682NKKJ+UJjC9xTDmUgkyoQARRvOdNEpLUJalx0/F2Rx40/6ewkIYCV+T1zqJi+xHmncejTpHvu3/8Ez1bfNVQgNniN/48iIPc+qzIjxRzi/6XupPf+5jjfKh4TTN2sPLZ+wGzKlB0PvncCSUbB2MEy/Z/aoFDre7NGXbhauVPUrB4v5Qheb8b6O78E0sF+Ki6NYO1gaz064sbFnd0ZlN68xB2l6pyf9/cDYZrWGWiAFKC14Jz6YqcFRoLKagaJWd5WlWsCvGEfElD8CgRZmmqlTO1Ccns+IU28vyieA=
    local_dir: dpl_cd_upload
    on: &3
      repo: Project-Heimdall/heimdall-hoard
      branch: $HEIMDALL_BRANCH_FOR_DEPLOY
    bucket: prod-heimdall-hoard-codedeploy
    region: us-west-2
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: *1
    secret_access_key: *2
    bucket: prod-heimdall-hoard-codedeploy
    key: $HEIMDALL_PACKAGE_NAME
    bundle_type: zip
    application: prod-heimdall-hoard-app
    deployment_group: prod-heimdall-hoard-group
    region: us-east-1
    on: *3
    skip_cleanup: true
