language: java
jdk: oraclejdk7
sudo: false
env:
  global:
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_BUILD_LABEL=$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-pre-alpha-$TRAVIS_BRANCH
  - HEIMDALL_BRANCH_FOR_DEPLOY=master
  - HEIMDALL_PACKAGE_NAME=hoard-ingest-1.0-SNAPSHOT-dist-assembly.zip
script:
  - mvn clean package -Pprod -DskipTests
before_deploy:
  - mkdir -p dpl_cd_upload
  - cp target/$HEIMDALL_PACKAGE_NAME dpl_cd_upload
deploy:
  - provider: s3
    access_key_id: &1
      secure: DrooVPxUBYUQSNoQtKohD0uL+Rn71GN2Lt8ooNnV2qEi7k2uK/Fnmlvh/eaL+IpNmyJ24mwdwfUBByQFBjoFTTonRmlODYkUSy02khtgvMGZIsLVCxsaqNyr9nccVGDLLC1RKv6w9rrZ63fbbwNY3Kfw0/dT3Iut4p7RrCpM+1ueSIKKUsKXoWHQH9Z3WCW1dfeRQx5CMjm9o93IivO9Bj48huL3Ww1ypxUhEcJFativgYEvhkZgOlrw/lzDqyEzMItXw+58+Nb1A6IglgZ3UHq7QTTM5eYLngR7jNSKffpPZ5fEfREf3ayfZhEhICU/pNfZg5takGBI/m+hzNjA8nhX22cJrnG9ntVQxrxdIOVLZ24N2RZG0inZM4PSZdw4/tS3H6pIFoZyf61t9N50NbO2trSgMjZgG1aKWZ4CvvLKAYSxcsmCWOn/PUTEPQ/pkcMN6GmjpOrTXA8YU7pN/clm2B6fk1h6Cm94/w214NcBI+u85seLf7GSq7KHSeDBcgpVULWT/dhI4JjpzdI/lK3F+gR7bsPyTlu+7eArJjtSjbL+0tOfcNyKLbC2uLmxpk0LxrFD9Ysk8TJrGiuJwShNrjloqAZ4284LvWyUogdafZdDSSz3fYx/qw5sbc3fYvJ7Mjwn4xAO8ZzSOiCAqwfX/W/1WhUMjI+mWSJaSD8=
    secret_access_key: &2
      secure: YzobwwCo0TqIFGp4M7b1u1sk21mJ6TvYim5Wb4RYRkPEFWCH5oD0291yOw5ktnTIbX9BRqhikzeifubY0KzeniTJlPCYYsNBXHQQ3WVLuR4XmoQAXzUu6eLoFx1L4Wu5J7OiNDFtEFEvxqKZxZ3ZgXJHHPfAdIaNzdDhVSsdn954vrhttSbFb/noWFanKDhi+cZXMJxtg8UnL2tV1DecgXmY6x1bUUTKNV4BymCKVXhPUv6v1H7Y9SdaUw2pci/W48EOzY6bdl6o32JD7uzTfUE7hZkr79Klo97aq1CDVUo6xyYmJO+Ib5jmaONhlFdk5dVmug1769wv27LFksDm6nNmiGg5GCa/4hu0KR8/nOBUQ4NcvmKYdSt4AZ9TCv4bqxkZ+e7NvekgqQnOtDTmITOFmBnbH8QMQ9hihjFUJ7QPSUisjDOsg2U/0tiuv2rEoysvacRlr3sX3dTnRLHGJklNrRTq8ZFN1sKHoqKL5kEMFq8RK9q7ZY3htjcQdm7T4PaW70yAZOnmOFPyTr18dCPKykd7yGo+XJxhVWLM8nd70+sK28dK189eUbEXWy/vKX0ygLZN4fDElkmsEnJtaTjqFSwGdaJ/X1MwbsiZwC6aJOVMlJuvmLOevc2vf7cOr4JsYAgfQvPhhfIGXPOIQcdAjIhHjoCo2ODkvQSt/RU=
    local_dir: dpl_cd_upload
    on: &3
      repo: Project-Heimdall/heimdall-hoard
      branch: $HEIMDALL_BRANCH_FOR_DEPLOY
    bucket: prod-heimdall-hoard-codedeploy
    region: us-west-2
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: *1
    secret_access_key: *2
    bucket: prod-heimdall-hoard-codedeploy
    key: $HEIMDALL_PACKAGE_NAME
    bundle_type: zip
    application: prod-heimdall-hoard-app
    deployment_group: prod-heimdall-hoard-group
    region: us-east-1
    on: *3
    skip_cleanup: true
