language: java
jdk: oraclejdk7
sudo: false
env:
  global:
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_BUILD_LABEL=$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-pre-alpha-$TRAVIS_BRANCH
  - HEIMDALL_BRANCH=development
  - HEIMDALL_PACKAGE_NAME=hoard-ingest-1.0-SNAPSHOT-dist-assembly.zip
script:
  - mvn clean package -DskipTests
before_deploy:
  - mkdir -p dpl_cd_upload
  - cp target/$HEIMDALL_PACKAGE_NAME dpl_cd_upload
deploy:
  - provider: s3
    access_key_id: &1
      secure: lQvjtJCe7qdl8Hsaqve+UdcqKFFZYWa7oQdgsse5ZVGeafBh8FzAn3OlqG6IaLaMS+HMaTnRAGiSiGZPiBmQLMIdVf4sDrwxRT7F0UBSHl2p6pdXM2KIxlSEGdYviu+1An1ozIyqZciI8Eqi20cbjhX9xiwR98h4rm2mZC0YpEWjMsx4y2Lk3aB4Z237q/+qlRIksYvrJpDvSknY33AbFMV4I2R1R+bHhV+TOnHbR/68nNLgVj0kZ+mioebljgc2/78tGG0cibM5zCTNBnjC2PjPSZOCI2ynMu4QLtOKHbKE7/cHnpTuS3o9UH+M28hHgL0NA4cj08ucuEJLA1aBcr7oMEDZeNljejtv2jFFIlSbdl/2BX3y3S1dspKMQCXbpUBw6UiE+YI1MM2RYHZJYNyw8Ua6p9f7KwlBKl04v+ALegP6/vVJJfjjifXqe4U9rtZjajxuYRUE+3ol+kJuFoTmZdSAGKb2TmB7NeZBrNZi8Nsfd29YTkt7dCKKMVMnvNjR759UtxSat1f6SVAJcfdJsyDtV8TpLk5FPwCJTSW3q02px/yz6LqYlHw+iinooFl0/c21nn6P/wmxdvSFoayXU/eICULecZ1zJhMGSNhBO7OYHhORWVD5FiaJBbAvYXxEBpqzdbw5iWPU3Nm3PoBVxU/rWjvgfM1i4La20Bo=
    secret_access_key: &2
      secure: C1H2gqTDNITIWspR4r6mo2iePYQhYTw6SQPgHfKjkOX8WQ7p15RTiKFtQDR5pmQjyy09LdZuVSJEItrGxVgCZfBpVpSxhkgzEQKcTHFKqkCHea3UMZBsXbDvsG7q0tsKxgxb2FjHVJ6DBRldcEQXYgNz8ZS0+ccKnfubUB6fhFw/RjeIs1ImhYDU/C2gFPB08ewawzkl544Wi9hAofOwBJRz/gS/R92Xqi8barhSW2JUxVx65UThaGSgCRFTgKIs7AKqGWcCidjNdtKJS43cMJthCUztrB56dmV9Le3VeUvHT3sx20mnwCEXjuL+PVF9J46sDaw2WZdM4xyVqLEsTtwAyvHZGQ9JxNskeQ4VyQvf1JeQCdz7T/IEYoOp7mO1zU2UeC1KR8Tm500o00Etq7+ond3qzgyQGB/cLTp4XwC3aleTguHUt8/V9zVWBNw6cUGDbDx52Zw4zA4Tf/dienk0uo8p83ic06L2sVjLhXnNXsPlBrLd3JRpQhsk83fSbGKqIwLjIFRCvtOSkLSLDPLY82UTs/USx2JokkyHwYmmYakd1TancyvTBkJfp/1gefmumbZe+QBCDgntDaZwluV57f/9VF77Rrmz2cy5ejE5G2sieU0fhfbk2vwgbFpXeJSGx4YaVRlBObB5by/5FrgL1flhWG8vpUVinZu4Bpo=
    local_dir: dpl_cd_upload
    on: &3
      repo: Project-Heimdall/heimdall-hoard
      branch: $HEIMDALL_BRANCH
    bucket: dev-heimdall-hoard-codedeploy
    region: us-west-2
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: *1
    secret_access_key: *2
    bucket: dev-heimdall-hoard-codedeploy
    key: $HEIMDALL_PACKAGE_NAME
    bundle_type: zip
    application: dev-heimdall-hoard-app
    deployment_group: dev-heimdall-hoard-group
    region: us-east-1
    on: *3
    skip_cleanup: true
