language: java
jdk: oraclejdk7
sudo: false
env:
  global:
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_BUILD_LABEL=$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-pre-alpha-$TRAVIS_BRANCH
  - HEIMDALL_BRANCH=development
  - HEIMDALL_PACKAGE_NAME=hoard-ingest-1.0-SNAPSHOT-dist-assembly.zip
script:
  - mvn clean package -Pdev -DskipTests
before_deploy:
  - mkdir -p dpl_cd_upload
  - cp target/$HEIMDALL_PACKAGE_NAME dpl_cd_upload
deploy:
  - provider: s3
    access_key_id: &1
      secure: lsNDZlc6bxe4gSaWxgKppQK9XQvbUBxD9FHhYq0F7UdP7JXQ5IxrEtBQeY4z6VO/tlDOYbw736ptRQjiUZkRBPycYk+y8raBYSElTAXoAYg2E8HGOEtgPqTCG5tlGXYKUiFhrWFznhSxKFjInGuUxNSjrZXDLXLYeqy2rI6YvWUcgm9ls2dR4RXdk/x39xwMhWHvuepUL59vy15nW05a1i+vGcV0NfE3zkGSttmT7Mhz8mPOYrCQbJOpmgEFNrnxURnmiqtsIE18a8oa2VtP2oAqTzysY4cKooPZgSzicXszFGNi3xgwVsFXWMkavIFnoIgmlEbw/Erwf3cHTgkmw4flUEl/woZRhHpkjZJ1+c/k9yGMx74NmH/BtRsZfs4mF3L50e7T2IgEu8e21aW0PnLQ3iJ2VSnST6Pf3Svv+exqkfAD5gJFJXMBDouYlr/xIajBcrOjs1NF8Ws6PZoWYYxWIZsQPXlaKrY/9jjK/AuefCJe4SVY8HQCPodg7ayaC/F4xTYjb+a/DOhDVKNkhIHKDby9SOLWHwUyVEADHgKjTmJp5NMck7IvEEguRvt3Cv4vMU3vjm/M7PO6vOBBYsPtD4wTFrM3uZRM9tgF9cJ57B+pbt4x1dfAftM453JqVQThuzDLFIOHUNUYWI72QtvJYjUbKwAJ9LjfgQ9rvOs=
    secret_access_key: &2
      secure: HZJwVIziEPFT0bLYjsos5GkQTdhUEHuQF5ymT4QEF9KPxjBrnrOhMXguMJriFpFTQBesSD5VJ4StZa8PkRlR+hIO+bmew1ehLUrdgBR4xQjdBRKupS9YYpFCKS3s1FUrxD9qJQhlPDZwWCwTSAJD86pMU8UaTjZrdQJ5yvTxQbSU8DmlLuaqt38/KlA9H4aA9nNuo0hcSXVVwXNWvFkfhJ7qM7g5se7qfEmlMWkoc0TjGLSp425UZhMmv4yM6jqkzfaiTd+utFYmYkV9I2ngPWcV0+WAQIjnJNJNnjeyZlyllSHk2hC6ibMEaAu1llQEzG+LxBxCluvKayI3X9Dx4NRJSmx5yOFwcc7WxuK4wWStEWDDtoWKcTYNOaXOq0023ktKdXT1j4CIQuJ5H9H0ny/ZPnkpyKN1H/mforQ/dRtsqbsH+JwiSlueJOGo2aNVemXG6MmBWOEGn3zkdeIHPJ0CGuIflns5NIjUTboTap+vFL9k0CzoYruct3XOArdpHJCXcTNh9FJgDxgii+Q+DMNg6o06WAXJnEXKuOjZvPm5isI0GpxytcdDU5og+u98NvMxX7jfMlEmBLBcaam0NQKA0bG53hliXIus3GXf430FOvovkXI4DcesUXTTIxnPSxLyPCITtayG0QSzLzha/ZbPlvB500rFNsbFhXu6SOw=
    local_dir: dpl_cd_upload
    on: &3
      repo: Project-Heimdall/heimdall-hoard
      branch: $HEIMDALL_BRANCH
    bucket: dev-stage-hoard-codedeploy
    region: us-west-2
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: *1
    secret_access_key: *2
    bucket: dev-stage-hoard-codedeploy
    key: $HEIMDALL_PACKAGE_NAME
    bundle_type: zip
    application: dev-stage-hoard-app
    deployment_group: dev-stage-hoard-group
    region: us-east-1
    on: *3
    skip_cleanup: true
