sonar:
  image: natesol15/stage-sonar
  ports:
    - 9000:9000
  links:
    - db:mysql
  environment:
    - SONAR_JDBC_URL=jdbc:mysql://mysql:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    - SONAR_DB_USERNAME=sonarqube
    - SONAR_DB_PASSWORD=sonarqube

db:
  image: mysql:5.6
  hostname: mysql
  ports:
    - 3306
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_USER=sonarqube
    - MYSQL_PASSWORD=sonarqube
    - MYSQL_DATABASE=sonarqube
